const $=id=>document.getElementById(id);let n=1,run=null,timer,hideTimer,paused=false,countdown=false,speechTimer;const letters=['C','H','K','L','Q','R','S','T'];let history=[];try{history=JSON.parse(localStorage.getItem('nback-history')||'[]');if(!Array.isArray(history))history=[]}catch{}const cells=Array.from({length:9},()=>{const el=document.createElement('div');el.className='cell';$('board').append(el);return el});
function renderHistory(){const host=$('history-list');host.replaceChildren();if(!history.length){host.innerHTML='<div class="empty">尚未有訓練記錄。完成第一回合，從這裡看見自己的練習。</div>';return}history.slice(0,5).forEach(h=>{const row=document.createElement('div');row.className='history-row';for(const text of [new Date(h.date).toLocaleString('zh-TW',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}),h.n+'-Back',h.trials+' 次',h.score+'% 正確率']){const el=document.createElement(text.includes('%')?'strong':'span');el.textContent=text;row.append(el)}host.append(row)})}
function update(){n=+$('level').value;$('level-display').textContent=n;$('level-label').textContent=n+' BACK';document.querySelectorAll('.n-text').forEach(e=>e.textContent=n);$('counter').textContent='0 / '+(+$('trials').value+n)+' 次'}
function controls(active){document.querySelectorAll('.settings input,.settings select,.stepper button').forEach(el=>el.disabled=active);$('pause').disabled=!active;$('stop').disabled=!active;$('position').disabled=!active||paused||countdown;$('audio').disabled=!active||paused||countdown}
function speak(letter){return trainingAudio.play(letter)}
function createSequence(total){const seq=[];for(let i=0;i<total;i++){const item={};for(const [key,size] of [['p',9],['s',8]]){if(i>=n&&Math.random()<.3)item[key]=seq[i-n][key];else{do{item[key]=Math.floor(Math.random()*size)}while(i>=n&&item[key]===seq[i-n][key])}}seq.push(item)}return seq}
function clearTimers(){clearTimeout(timer);clearTimeout(hideTimer);clearTimeout(speechTimer)}
function resetButtons(){for(const id of ['position','audio']){$(id).classList.remove('selected');$(id).querySelector('.response-mark').textContent='＋'}}
function scoreTrial(){if(run.index<n)return;const item=run.seq[run.index],prev=run.seq[run.index-n];for(const [channel,key] of [['position','p'],['audio','s']]){const match=item[key]===prev[key],pressed=run.response[channel];const s=run.stats[channel];if(match&&pressed)s.hit++;else if(match)s.miss++;else if(pressed)s.false++;else s.correct++}}
function next(){if(!run||paused)return;if(run.index>=0)scoreTrial();run.index++;if(run.index===run.seq.length){finish(true);return}run.response={position:false,audio:false};resetButtons();cells.forEach(el=>el.classList.remove('active'));cells[run.seq[run.index].p].classList.add('active');speak(letters[run.seq[run.index].s]);$('counter').textContent=(run.index+1)+' / '+run.seq.length+' 次';$('progress').style.width=((run.index+1)/run.seq.length*100)+'%';$('message').textContent=run.index<n?'暖身中：先記住訊號，這次不計分。':'與前 '+n+' 次比對；相同才按鍵。';hideTimer=setTimeout(()=>cells.forEach(el=>el.classList.remove('active')),Math.min(700,run.interval/2));timer=setTimeout(next,run.interval)}
async function start(){if(run||trainingAudio.loading)return;try{await trainingAudio.prepare()}catch{$('message').textContent='聲音載入失敗，請檢查網路後再試。';return}n=+$('level').value;paused=false;countdown=true;run={seq:createSequence(+$('trials').value+n),index:-1,interval:+$('speed').value,response:{},stats:{position:{hit:0,miss:0,false:0,correct:0},audio:{hit:0,miss:0,false:0,correct:0}}};controls(true);$('pause').textContent='暫停';$('state').textContent='準備中';$('progress').style.width='0';let remaining=3;$('overlay').innerHTML='<span class="score" id="countdown">3</span><p>記住位置與聲音</p>';$('overlay').style.display='flex';const tick=()=>{if(paused||!run)return;remaining--;if(remaining>0){$('countdown').textContent=remaining;timer=setTimeout(tick,1000)}else{countdown=false;$('overlay').style.display='none';$('state').textContent='訓練中';controls(true);next()}};timer=setTimeout(tick,1000)}
function answer(channel){if(!run||paused||countdown||run.index<0||run.response[channel])return;run.response[channel]=true;$(channel).classList.add('selected');$(channel).querySelector('.response-mark').textContent='✓'}
function togglePause(){if(!run)return;if(countdown){finish(false);return}paused=!paused;clearTimers();trainingAudio.stop();controls(true);$('pause').textContent=paused?'繼續':'暫停';$('state').textContent=paused?'已暫停':'訓練中';if(paused){cells.forEach(el=>el.classList.remove('active'));$('overlay').innerHTML='<span class="ready-icon">Ⅱ</span><h2>稍作休息</h2><p>繼續時會重新播放這次訊號。</p><button id="resume" class="primary">繼續訓練</button>';$('overlay').style.display='flex';$('resume').onclick=togglePause}else{$('overlay').style.display='none';cells[run.seq[run.index].p].classList.add('active');speak(letters[run.seq[run.index].s]);hideTimer=setTimeout(()=>cells.forEach(el=>el.classList.remove('active')),700);timer=setTimeout(next,run.interval)}}
function finish(completed){clearTimers();trainingAudio.stop();cells.forEach(el=>el.classList.remove('active'));paused=false;countdown=false;controls(false);resetButtons();$('state').textContent=completed?'訓練完成':'訓練已結束';let detail='未完成的回合不會儲存成績。',title='準備再試一次';if(completed){const trials=run.seq.length-n;const p=run.stats.position,a=run.stats.audio;const score=Math.round((p.hit+p.correct+a.hit+a.correct)/(trials*2)*100);history.unshift({date:Date.now(),n,trials,score});history=history.slice(0,50);try{localStorage.setItem('nback-history',JSON.stringify(history))}catch{}renderHistory();title='<span class="score">'+score+'<small>%</small></span>';detail='位置：命中 '+p.hit+' · 漏答 '+p.miss+' · 誤按 '+p.false+'<br>聲音：命中 '+a.hit+' · 漏答 '+a.miss+' · 誤按 '+a.false+'<br>正確率包含正確比對與正確不作答。'}run=null;$('overlay').innerHTML='<h2>'+title+'</h2><p>每一次練習，都是新的開始。</p><div class="score-detail">'+detail+'</div><button id="restart" class="primary">再練一回合 ↗</button>';$('overlay').style.display='flex';$('restart').onclick=start;$('message').textContent=completed?'成績已儲存。可調整難度後再開始。':'可調整設定，再次開始。'}
$('start').onclick=start;$('position').onclick=()=>answer('position');$('audio').onclick=()=>answer('audio');$('pause').onclick=togglePause;$('stop').onclick=()=>finish(false);$('level').oninput=update;$('trials').onchange=update;$('minus').onclick=()=>{$('level').value=Math.max(1,n-1);update()};$('plus').onclick=()=>{$('level').value=Math.min(8,n+1);update()};$('sound-test').onclick=async()=>{if(!run){try{await trainingAudio.prepare();speak('C')}catch{$('message').textContent='聲音載入失敗，請再試一次。'}}};$('help').onclick=()=>{if(run&&!paused)togglePause();$('help-dialog').showModal()};for(const id of ['close-help','understood'])$(id).onclick=()=>$('help-dialog').close();document.addEventListener('keydown',e=>{if(e.repeat||$('help-dialog').open||['SELECT','INPUT'].includes(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();run?togglePause():start()}else if(e.key.toLowerCase()==='a')answer('position');else if(e.key.toLowerCase()==='l')answer('audio')});document.addEventListener('visibilitychange',()=>{if(document.hidden&&run&&!paused){if(countdown)finish(false);else togglePause()}});update();renderHistory();
